import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Analytics from "@/components/shared/analytics";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hashtel Technology Pvt. Ltd.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics/>
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
