import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleTagManager, GoogleAnalytics } from "@next/third-parties/google";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hashtel Technology Pvt. Ltd.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-N43PJ8S6" />
      <GoogleAnalytics gaId="G-GEWNY1PFXC" />
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
